[build-system]
requires = ["uv_build>=0.7.20"]
build-backend = "uv_build"

[project]
name = "dmsuite"
version = "0.3.0"
description = "Differentiation matrices"
readme = "README.md"
authors = [
    {name = "Adrien Morison", email = "adrien.morison@gmail.com"},
    {name = "Stéphane Labrosse"},
]
maintainers = [
    {name = "Adrien Morison", email = "adrien.morison@gmail.com"},
    {name = "Stéphane Labrosse"},
]
license = "GPL-2.0-only"
license-files = ["LICENSE"]
urls = {homepage = "https://github.com/labrosse/dmsuite"}
classifiers=[
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.0",
    "scipy>=1.13",
]

[tool.uv.build-backend]
module-root = ""

[tool.mypy]
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = [
    "scipy.*",
]
ignore_missing_imports = true

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.2",
    "pytest-cov>=5.0.0",
    "mypy>=1.11.2",
    "ruff>=0.6.2",
]
